### ISSUE TITLE
How to format conversion

### ISSUE THREAD

**Issue by wangxin-fighting** [2Obe/BSData#6]
Hello, how can I convert  annotation in the "JSON" format to mask maps in the "png" format?

**Comment by sungsy** [comment]
Since the labeling was done with `labelme` - I recommend to check out it's [github](https://github.com/wkentaro/labelme/tree/main) - there you can convert the labels to `.png`. Being more specific as in this [issue](https://github.com/wkentaro/labelme/issues/772#issuecomment-931360748) suggested you can use `labelme2coco.py` or `labelme2voc.py`.
